### ISSUE TITLE
missing module ./BasedGuildEmoji

### ISSUE THREAD

**Issue by Hades3377** [Milo123459/NewTutorialBot#1]

**Comment by Hades3377** [comment]
why did u close
do you know a solution?

**Comment by Milo123459** [comment]
This is a blank issue.

**Comment by Hades3377** [comment]
pretty sure the title sums it up, the module itself is missing, unless you would like an entire copy and paste of the error

**Comment by Hades3377** [comment]
Error: Cannot find module './BaseGuildEmoji'
Require stack:
- C:\Users\Hades\Desktop\Jaxxy final'\node_modules\discord.js\src\structures\GuildEmoji.js
- C:\Users\Hades\Desktop\Jaxxy final'\node_modules\discord.js\src\managers\GuildEmojiManager.js
- C:\Users\Hades\Desktop\Jaxxy final'\node_modules\discord.js\src\client\Client.js
- C:\Users\Hades\Desktop\Jaxxy final'\node_modules\discord.js\src\index.js

**Comment by Milo123459** [comment]
Run in the terminal
npm uninstall discord.js
then
npm i discord.js


I hope this helps.

**Comment by Hades3377** [comment]
aight works, just adds a few more code errors that can be cleaned up easily.

**Comment by Milo123459** [comment]
Glad to know I could help
